CREATE TYPE "public"."tool_source" AS ENUM('seed', 'user', 'llm', 'admin');--> statement-breakpoint
CREATE TYPE "public"."tool_status" AS ENUM('active', 'blocked');--> statement-breakpoint
ALTER TABLE "tools" ADD COLUMN "status" "tool_status" DEFAULT 'active' NOT NULL;--> statement-breakpoint
ALTER TABLE "tools" ADD COLUMN "source" "tool_source" DEFAULT 'seed' NOT NULL;--> statement-breakpoint
ALTER TABLE "tools" ADD COLUMN "created_by_user_id" text;--> statement-breakpoint
ALTER TABLE "tools" ADD COLUMN "usage_count" integer DEFAULT 0 NOT NULL;--> statement-breakpoint
ALTER TABLE "tools" ADD COLUMN "created_at" timestamp DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "tools" ADD COLUMN "updated_at" timestamp DEFAULT now() NOT NULL;--> statement-breakpoint
ALTER TABLE "tools" ADD CONSTRAINT "tools_created_by_user_id_user_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "tools_status_idx" ON "tools" USING btree ("status");
--> statement-breakpoint
INSERT INTO "tools" ("name", "slug", "status", "source", "usage_count")
VALUES
  ('Claude', 'claude', 'active', 'seed', 0),
  ('ChatGPT', 'chatgpt', 'active', 'seed', 0),
  ('Cursor', 'cursor', 'active', 'seed', 0),
  ('GitHub Copilot', 'github-copilot', 'active', 'seed', 0),
  ('v0', 'v0', 'active', 'seed', 0),
  ('Bolt', 'bolt', 'active', 'seed', 0),
  ('Replit Agent', 'replit-agent', 'active', 'seed', 0),
  ('Windsurf', 'windsurf', 'active', 'seed', 0),
  ('Next.js', 'nextjs', 'active', 'seed', 0),
  ('React', 'react', 'active', 'seed', 0),
  ('Vue', 'vue', 'active', 'seed', 0),
  ('Svelte', 'svelte', 'active', 'seed', 0),
  ('Astro', 'astro', 'active', 'seed', 0),
  ('Remix', 'remix', 'active', 'seed', 0),
  ('Nuxt', 'nuxt', 'active', 'seed', 0),
  ('SvelteKit', 'sveltekit', 'active', 'seed', 0),
  ('Node.js', 'nodejs', 'active', 'seed', 0),
  ('Express', 'express', 'active', 'seed', 0),
  ('Hono', 'hono', 'active', 'seed', 0),
  ('Fastify', 'fastify', 'active', 'seed', 0),
  ('tRPC', 'trpc', 'active', 'seed', 0),
  ('PostgreSQL', 'postgresql', 'active', 'seed', 0),
  ('MySQL', 'mysql', 'active', 'seed', 0),
  ('SQLite', 'sqlite', 'active', 'seed', 0),
  ('MongoDB', 'mongodb', 'active', 'seed', 0),
  ('Supabase', 'supabase', 'active', 'seed', 0),
  ('PlanetScale', 'planetscale', 'active', 'seed', 0),
  ('Neon', 'neon', 'active', 'seed', 0),
  ('Turso', 'turso', 'active', 'seed', 0),
  ('Drizzle', 'drizzle', 'active', 'seed', 0),
  ('Prisma', 'prisma', 'active', 'seed', 0),
  ('Tailwind CSS', 'tailwindcss', 'active', 'seed', 0),
  ('shadcn/ui', 'shadcn-ui', 'active', 'seed', 0),
  ('Radix UI', 'radix-ui', 'active', 'seed', 0),
  ('Vercel', 'vercel', 'active', 'seed', 0),
  ('Netlify', 'netlify', 'active', 'seed', 0),
  ('Cloudflare', 'cloudflare', 'active', 'seed', 0),
  ('Railway', 'railway', 'active', 'seed', 0),
  ('Fly.io', 'fly-io', 'active', 'seed', 0),
  ('Render', 'render', 'active', 'seed', 0),
  ('Better Auth', 'better-auth', 'active', 'seed', 0),
  ('NextAuth', 'nextauth', 'active', 'seed', 0),
  ('Clerk', 'clerk', 'active', 'seed', 0),
  ('Auth0', 'auth0', 'active', 'seed', 0),
  ('TypeScript', 'typescript', 'active', 'seed', 0),
  ('Zod', 'zod', 'active', 'seed', 0),
  ('React Query', 'react-query', 'active', 'seed', 0),
  ('JavaScript', 'javascript', 'active', 'seed', 0),
  ('Python', 'python', 'active', 'seed', 0),
  ('Java', 'java', 'active', 'seed', 0),
  ('C#', 'c-sharp', 'active', 'seed', 0),
  ('C++', 'c-plus-plus', 'active', 'seed', 0),
  ('C', 'c', 'active', 'seed', 0),
  ('Go', 'go', 'active', 'seed', 0),
  ('PHP', 'php', 'active', 'seed', 0),
  ('Ruby', 'ruby', 'active', 'seed', 0),
  ('Swift', 'swift', 'active', 'seed', 0),
  ('Kotlin', 'kotlin', 'active', 'seed', 0),
  ('Rust', 'rust', 'active', 'seed', 0),
  ('Dart', 'dart', 'active', 'seed', 0),
  ('Scala', 'scala', 'active', 'seed', 0),
  ('R', 'r', 'active', 'seed', 0),
  ('SQL', 'sql', 'active', 'seed', 0),
  ('Bash', 'bash', 'active', 'seed', 0),
  ('PowerShell', 'powershell', 'active', 'seed', 0),
  ('Lua', 'lua', 'active', 'seed', 0),
  ('Perl', 'perl', 'active', 'seed', 0),
  ('Objective-C', 'objective-c', 'active', 'seed', 0),
  ('MATLAB', 'matlab', 'active', 'seed', 0),
  ('Julia', 'julia', 'active', 'seed', 0),
  ('Haskell', 'haskell', 'active', 'seed', 0),
  ('OCaml', 'ocaml', 'active', 'seed', 0),
  ('Clojure', 'clojure', 'active', 'seed', 0),
  ('Elixir', 'elixir', 'active', 'seed', 0),
  ('Erlang', 'erlang', 'active', 'seed', 0),
  ('F#', 'f-sharp', 'active', 'seed', 0),
  ('Groovy', 'groovy', 'active', 'seed', 0),
  ('Assembly (x86/ARM)', 'assembly-x86-arm', 'active', 'seed', 0),
  ('Zig', 'zig', 'active', 'seed', 0),
  ('Nim', 'nim', 'active', 'seed', 0),
  ('Crystal', 'crystal', 'active', 'seed', 0),
  ('Solidity', 'solidity', 'active', 'seed', 0),
  ('Move', 'move', 'active', 'seed', 0),
  ('Prolog', 'prolog', 'active', 'seed', 0),
  ('Fortran', 'fortran', 'active', 'seed', 0),
  ('COBOL', 'cobol', 'active', 'seed', 0),
  ('Deno', 'deno', 'active', 'seed', 0),
  ('Bun', 'bun', 'active', 'seed', 0),
  ('JVM', 'jvm', 'active', 'seed', 0),
  ('.NET', 'net', 'active', 'seed', 0),
  ('CPython', 'cpython', 'active', 'seed', 0),
  ('PyPy', 'pypy', 'active', 'seed', 0),
  ('V8', 'v8', 'active', 'seed', 0),
  ('WebAssembly', 'webassembly', 'active', 'seed', 0),
  ('Android Runtime (ART)', 'android-runtime-art', 'active', 'seed', 0),
  ('Copilot Chat', 'copilot-chat', 'active', 'seed', 0),
  ('GitHub Copilot Agents', 'github-copilot-agents', 'active', 'seed', 0),
  ('OpenAI Codex', 'openai-codex', 'active', 'seed', 0),
  ('Claude Code', 'claude-code', 'active', 'seed', 0),
  ('JetBrains AI Assistant', 'jetbrains-ai-assistant', 'active', 'seed', 0),
  ('Amazon Q Developer', 'amazon-q-developer', 'active', 'seed', 0),
  ('Gemini Code Assist', 'gemini-code-assist', 'active', 'seed', 0),
  ('Replit AI', 'replit-ai', 'active', 'seed', 0),
  ('Sourcegraph Cody', 'sourcegraph-cody', 'active', 'seed', 0),
  ('Tabnine', 'tabnine', 'active', 'seed', 0),
  ('Codeium', 'codeium', 'active', 'seed', 0),
  ('Continue', 'continue', 'active', 'seed', 0),
  ('Aider', 'aider', 'active', 'seed', 0),
  ('Bolt.new', 'bolt-new', 'active', 'seed', 0),
  ('Lovable', 'lovable', 'active', 'seed', 0),
  ('Devin', 'devin', 'active', 'seed', 0),
  ('Perplexity', 'perplexity', 'active', 'seed', 0),
  ('Pieces for Developers', 'pieces-for-developers', 'active', 'seed', 0),
  ('CodeQL', 'codeql', 'active', 'seed', 0),
  ('Angular', 'angular', 'active', 'seed', 0),
  ('Gatsby', 'gatsby', 'active', 'seed', 0),
  ('SolidJS', 'solidjs', 'active', 'seed', 0),
  ('Qwik', 'qwik', 'active', 'seed', 0),
  ('Lit', 'lit', 'active', 'seed', 0),
  ('Web Components', 'web-components', 'active', 'seed', 0),
  ('React Router', 'react-router', 'active', 'seed', 0),
  ('Vue Router', 'vue-router', 'active', 'seed', 0),
  ('Redux', 'redux', 'active', 'seed', 0),
  ('Zustand', 'zustand', 'active', 'seed', 0),
  ('MobX', 'mobx', 'active', 'seed', 0),
  ('TanStack Query', 'tanstack-query', 'active', 'seed', 0),
  ('SWR', 'swr', 'active', 'seed', 0),
  ('Apollo Client', 'apollo-client', 'active', 'seed', 0),
  ('Relay', 'relay', 'active', 'seed', 0),
  ('Bootstrap', 'bootstrap', 'active', 'seed', 0),
  ('Material UI', 'material-ui', 'active', 'seed', 0),
  ('Chakra UI', 'chakra-ui', 'active', 'seed', 0),
  ('Ant Design', 'ant-design', 'active', 'seed', 0),
  ('Styled Components', 'styled-components', 'active', 'seed', 0),
  ('Emotion', 'emotion', 'active', 'seed', 0),
  ('Sass', 'sass', 'active', 'seed', 0),
  ('PostCSS', 'postcss', 'active', 'seed', 0),
  ('Storybook', 'storybook', 'active', 'seed', 0),
  ('Vite', 'vite', 'active', 'seed', 0),
  ('Webpack', 'webpack', 'active', 'seed', 0),
  ('Rollup', 'rollup', 'active', 'seed', 0),
  ('esbuild', 'esbuild', 'active', 'seed', 0),
  ('SWC', 'swc', 'active', 'seed', 0),
  ('Babel', 'babel', 'active', 'seed', 0),
  ('ESLint', 'eslint', 'active', 'seed', 0),
  ('Prettier', 'prettier', 'active', 'seed', 0),
  ('Turborepo', 'turborepo', 'active', 'seed', 0),
  ('Nx', 'nx', 'active', 'seed', 0),
  ('npm', 'npm', 'active', 'seed', 0),
  ('Yarn', 'yarn', 'active', 'seed', 0),
  ('pnpm', 'pnpm', 'active', 'seed', 0),
  ('Jest', 'jest', 'active', 'seed', 0),
  ('Vitest', 'vitest', 'active', 'seed', 0),
  ('React Testing Library', 'react-testing-library', 'active', 'seed', 0),
  ('Playwright', 'playwright', 'active', 'seed', 0),
  ('Cypress', 'cypress', 'active', 'seed', 0),
  ('Selenium', 'selenium', 'active', 'seed', 0),
  ('NestJS', 'nestjs', 'active', 'seed', 0),
  ('Koa', 'koa', 'active', 'seed', 0),
  ('Hapi', 'hapi', 'active', 'seed', 0),
  ('GraphQL', 'graphql', 'active', 'seed', 0),
  ('Apollo Server', 'apollo-server', 'active', 'seed', 0),
  ('Socket.IO', 'socket-io', 'active', 'seed', 0),
  ('Django', 'django', 'active', 'seed', 0),
  ('Flask', 'flask', 'active', 'seed', 0),
  ('FastAPI', 'fastapi', 'active', 'seed', 0),
  ('Starlette', 'starlette', 'active', 'seed', 0),
  ('Celery', 'celery', 'active', 'seed', 0),
  ('Spring Boot', 'spring-boot', 'active', 'seed', 0),
  ('Spring Security', 'spring-security', 'active', 'seed', 0),
  ('Quarkus', 'quarkus', 'active', 'seed', 0),
  ('Micronaut', 'micronaut', 'active', 'seed', 0),
  ('Dropwizard', 'dropwizard', 'active', 'seed', 0),
  ('ASP.NET Core', 'asp-net-core', 'active', 'seed', 0),
  ('Entity Framework Core', 'entity-framework-core', 'active', 'seed', 0),
  ('Ruby on Rails', 'ruby-on-rails', 'active', 'seed', 0),
  ('Sinatra', 'sinatra', 'active', 'seed', 0),
  ('Laravel', 'laravel', 'active', 'seed', 0),
  ('Symfony', 'symfony', 'active', 'seed', 0),
  ('Gin', 'gin', 'active', 'seed', 0),
  ('Fiber', 'fiber', 'active', 'seed', 0),
  ('Echo', 'echo', 'active', 'seed', 0),
  ('Actix Web', 'actix-web', 'active', 'seed', 0),
  ('Axum', 'axum', 'active', 'seed', 0),
  ('Rocket', 'rocket', 'active', 'seed', 0),
  ('Tokio', 'tokio', 'active', 'seed', 0),
  ('SwiftUI', 'swiftui', 'active', 'seed', 0),
  ('UIKit', 'uikit', 'active', 'seed', 0),
  ('Jetpack Compose', 'jetpack-compose', 'active', 'seed', 0),
  ('Android SDK', 'android-sdk', 'active', 'seed', 0),
  ('Flutter', 'flutter', 'active', 'seed', 0),
  ('React Native', 'react-native', 'active', 'seed', 0),
  ('Expo', 'expo', 'active', 'seed', 0),
  ('Ionic', 'ionic', 'active', 'seed', 0),
  ('Capacitor', 'capacitor', 'active', 'seed', 0),
  ('Apache Kafka', 'apache-kafka', 'active', 'seed', 0),
  ('Kafka Connect', 'kafka-connect', 'active', 'seed', 0),
  ('Apache Spark', 'apache-spark', 'active', 'seed', 0),
  ('Apache Flink', 'apache-flink', 'active', 'seed', 0),
  ('Airflow', 'airflow', 'active', 'seed', 0),
  ('Dagster', 'dagster', 'active', 'seed', 0),
  ('Prefect', 'prefect', 'active', 'seed', 0),
  ('dbt', 'dbt', 'active', 'seed', 0),
  ('Docker', 'docker', 'active', 'seed', 0),
  ('Kubernetes', 'kubernetes', 'active', 'seed', 0),
  ('Helm', 'helm', 'active', 'seed', 0),
  ('Terraform', 'terraform', 'active', 'seed', 0),
  ('Nginx', 'nginx', 'active', 'seed', 0),
  ('Envoy', 'envoy', 'active', 'seed', 0),
  ('OpenTelemetry', 'opentelemetry', 'active', 'seed', 0),
  ('Firebase', 'firebase', 'active', 'seed', 0),
  ('AWS', 'aws', 'active', 'seed', 0),
  ('Google Cloud', 'google-cloud', 'active', 'seed', 0),
  ('Microsoft Azure', 'microsoft-azure', 'active', 'seed', 0),
  ('Heroku', 'heroku', 'active', 'seed', 0),
  ('MongoDB Atlas', 'mongodb-atlas', 'active', 'seed', 0),
  ('CockroachDB Cloud', 'cockroachdb-cloud', 'active', 'seed', 0),
  ('Upstash', 'upstash', 'active', 'seed', 0),
  ('Algolia', 'algolia', 'active', 'seed', 0),
  ('Okta', 'okta', 'active', 'seed', 0),
  ('Keycloak', 'keycloak', 'active', 'seed', 0),
  ('Stripe', 'stripe', 'active', 'seed', 0),
  ('PayPal', 'paypal', 'active', 'seed', 0),
  ('Adyen', 'adyen', 'active', 'seed', 0),
  ('Braintree', 'braintree', 'active', 'seed', 0),
  ('Twilio', 'twilio', 'active', 'seed', 0),
  ('SendGrid', 'sendgrid', 'active', 'seed', 0),
  ('Mailgun', 'mailgun', 'active', 'seed', 0),
  ('Postmark', 'postmark', 'active', 'seed', 0),
  ('Sentry', 'sentry', 'active', 'seed', 0),
  ('Datadog', 'datadog', 'active', 'seed', 0),
  ('New Relic', 'new-relic', 'active', 'seed', 0),
  ('Grafana Cloud', 'grafana-cloud', 'active', 'seed', 0),
  ('Elastic Cloud', 'elastic-cloud', 'active', 'seed', 0),
  ('Honeycomb', 'honeycomb', 'active', 'seed', 0),
  ('PagerDuty', 'pagerduty', 'active', 'seed', 0),
  ('Google Analytics', 'google-analytics', 'active', 'seed', 0),
  ('Segment', 'segment', 'active', 'seed', 0),
  ('PostHog', 'posthog', 'active', 'seed', 0),
  ('Mixpanel', 'mixpanel', 'active', 'seed', 0),
  ('Amplitude', 'amplitude', 'active', 'seed', 0),
  ('LaunchDarkly', 'launchdarkly', 'active', 'seed', 0),
  ('Unleash', 'unleash', 'active', 'seed', 0),
  ('GitHub', 'github', 'active', 'seed', 0),
  ('GitHub Actions', 'github-actions', 'active', 'seed', 0),
  ('GitLab', 'gitlab', 'active', 'seed', 0),
  ('CircleCI', 'circleci', 'active', 'seed', 0),
  ('Figma', 'figma', 'active', 'seed', 0),
  ('Jira', 'jira', 'active', 'seed', 0),
  ('NumPy', 'numpy', 'active', 'seed', 0),
  ('Pandas', 'pandas', 'active', 'seed', 0),
  ('Requests', 'requests', 'active', 'seed', 0),
  ('httpx', 'httpx', 'active', 'seed', 0),
  ('Pydantic', 'pydantic', 'active', 'seed', 0),
  ('SQLAlchemy', 'sqlalchemy', 'active', 'seed', 0),
  ('pytest', 'pytest', 'active', 'seed', 0),
  ('Lodash', 'lodash', 'active', 'seed', 0),
  ('Chalk', 'chalk', 'active', 'seed', 0),
  ('Axios', 'axios', 'active', 'seed', 0),
  ('date-fns', 'date-fns', 'active', 'seed', 0),
  ('Three.js', 'three-js', 'active', 'seed', 0)
ON CONFLICT DO NOTHING;
